### ISSUE TITLE
What is this project used for?

### ISSUE THREAD

**Issue by utkarshcmu** [raintank/tsdb-gw#13]
Is it a web server for something?

**Comment by Dieterbe** [comment]
Hey Utkarsh. Tsdb-gw is our api gateway that sits in front of graphite-api+metrictank, elasticsearch and kafka.  It authenticates clients using key authentication and is able to ingest metrics and events (which it puts into our kafka queue) and it also serves as a query endpoint to add auth on top of graphite/elasticsearch.

**Comment by utkarshcmu** [comment]
Got it. Thanks @Dieterbe :)
