### ISSUE TITLE
ingestion Rate Limits

### ISSUE THREAD

**Issue by DanCech** [raintank/tsdb-gw#134]
Currently if a customer starts to send more metrics than their deployment is sized for we can run into issues with tsdb-gw or other components in the stack using too much memory and being killed by k8s, etc.  This results in the user getting nasty error messages like 504 gateway timeouts from nginx or 500 backend errors.

It would be much nicer if tsdb-gw had a rate-limiting capability that we could set to protect the system and instead return a 429 error that explains to the user that they're exceeding their provisioned capacity and should contact us to adjust their plan.

This would also be helpful in the multi-tenant deployments as it would give us a way to prevent a single user from vastly exceeding the capacity we expect them to use on the cluster.

**Comment by Dieterbe** [comment]
this means we should also do experiments and confirm what amounts of rate/s, active series, etc correspond to which amounts of ram and cpu.

**Comment by replay** [comment]
how does that interact with POSTs that push a large number of metrics in one request? f.e. if a user has a ratelimit of 1000 datapoints/sec, then they submit a single POST which includes 1001 datapoints, should the response be a 429 after 1000 have been processed? In that situation CRNG will resend all the 1001 datapoints, while holding off with newer datapoints to prevent out of order, resulting in a loop which blocks everything. So we should probably only reply with 429 to the requests where all included metrics are above the limit and process the previous requests fully even if we exceed the limit by doing that.

**Comment by tomwilkie** [comment]
Not sure this issue is relevant for cortex-gw (which lives in this repo), as Cortex implements all these rate limits itself.  I'd like to ensure cortex-gw remains stateless (therefore it can't track active series) and doesn't parse the requests (which can be expensive and I don't want to add any more latency).

**Comment by Dieterbe** [comment]
seeing this affect another HM customer that was increasing their MT index size and resulting in slow queries.
I think we should bump the priority of this

**Comment by Dieterbe** [comment]
let's keep this ticket for rate limit on datapoint volume.
for other limits, such as on active series, request workload etc, we have another project in the process of being specced out.
