### ISSUE TITLE
cluster migrations

### ISSUE THREAD

**Issue by Dieterbe** [raintank/tsdb-gw#160]
we need support for cluster migrations.
awoods and myself have a design doc draft, it needs to be cleaned up
https://docs.google.com/document/d/1IhrA-ENcMR7yhEQeuhBxcTOmDu9M-Dw1VhlOpw-g-us/edit

**Comment by fkaleo** [comment]
Moved to hm-api https://github.com/raintank/hosted-metrics-api/issues/288
