### ISSUE TITLE
monitor data timestamps "sync" with wall clock

### ISSUE THREAD

**Issue by Dieterbe** [raintank/tsdb-gw#162]
I would like to have a metric showing how far behind or ahead incoming metrics are wrt wall clock.
why?
1) it's useful for debugging/general understanding
2) it helps knowing how much overlap we need between old and new write pods during migrations (see #160)

instead of reporting, we may as well report the min and max timestamps seen at each point.
that provides more information, and it should be easy to derive the min/max lag numbers from that.

**Comment by woodsaj** [comment]
For adhoc analysis you can just look at the Kafka messages.   Each Kafka message has its own timestamp of when the message was created. https://godoc.org/github.com/Shopify/sarama#ConsumerMessage

So it would be trivial to write a tool that consumes from Kafka and compares the message timestamp with the data point timestamp

**Comment by Dieterbe** [comment]
That would be needless overhead both on Kafka as well as the operator. Seems much simpler to just measure it with a stat.

**Comment by woodsaj** [comment]
> That would be needless overhead both on Kafka as well as the operator.

How is doing adhoc analysis an overhead?

I would definitely recommend that before investing time in instrumenting anything you do some adhoc analysis to immediately get a better understanding of the lag of points being ingested.

**Comment by Dieterbe** [comment]
because it requires running the tooling and processing the messages, and because it will consume all data from the kafka topic.

comparing data timestamps against the clock and sending it out via a metric is close to free. and all the stats will always be available for all environments and can be easily consumed.

**Comment by woodsaj** [comment]
Why not do all of this in metrictank using the kafka message timestamp.  In addition to the lag between the datapoint timestamp and when we received it, you can also collect the lag between when we received it and when MT processed it.

**Comment by Dieterbe** [comment]
doing it in MT only would mean the data becomes messy every time a pod restarts.
so both seem useful, for different reasons.
