### ISSUE TITLE
Cluster enforcement for cortex isn't working

### ISSUE THREAD

**Issue by tomwilkie** [raintank/tsdb-gw#173]
We have a customer sending data to the wrong cluster. 

This shows the data is going to us-central1: https://admin-ops-tools1.grafana.net/grafana/explore?orgId=1&left=%5B%22now-6h%22,%22now%22,%22ops-tools1%22,%7B%22expr%22:%22sum%20by%20(cluster)%20(rate(cortex_distributor_received_samples_total%7Buser%3D%5C%228227%5C%22%7D%5B1m%5D))%22,%22context%22:%22explore%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

But this shows the cluster is set to eu-west2: https://grafana.com/api/hosted-metrics/8227

This lead us to mistakenly believing the customer was sending data correctly (the billing dashboard doesn't include cluster) but queries failing.

**Comment by woodsaj** [comment]
This is simply a configuration problem.
The cortex-gw's are configured with
```
      - -auth-validation-dry-run=true
```

```
	flag.BoolVar(&validationDryRun, "auth-validation-dry-run", true, "if true, invalid instance type and cluster would just cause logging of the bad requests but not an actual failure of the request.")
```

**Comment by tomwilkie** [comment]
Can we leave this open until Jacob has had a chance to roll this out?

Before enabling it we'll need to see if any users are sending data to the wrong cluster.

**Comment by woodsaj** [comment]
This issue doesn't belong here, it belongs in deployment_tools. I have opened an issue there.
https://github.com/raintank/deployment_tools/issues/1273
