### ISSUE TITLE
forward delete api endpoint to metrictank

### ISSUE THREAD

**Issue by Dieterbe** [raintank/tsdb-gw#21]
so that customers can delete their own series
everybody saves time, both customers and us -> win-win

**Comment by replay** [comment]
As far as I can see `tsdb-gw` doesn't block `DELETE` requests, in my local test env it's passing them through to `graphite-api`. But `graphite-api` then responds with a `405`. 
![1](https://cloud.githubusercontent.com/assets/195371/22384416/266a3e20-e4c6-11e6-923e-7864ffce9e64.png)
I'll create a related issue in `graphite-api`.

**Comment by Dieterbe** [comment]
delete requests should go to metrictank directly, and not involve graphite

**Comment by replay** [comment]
Ah, i see. Ok

**Comment by replay** [comment]
@Dieterbe  Looking at the Metrictank routes it seems like the intention is to delete via a `GET` request to `/index/delete` and not via a `DELETE` request. Is that right? Do we not use `GET` for deletes?
