### ISSUE TITLE
metrics sent to tsdb-gw are not being sent to Kafka correctly

### ISSUE THREAD

**Issue by woodsaj** [raintank/tsdb-gw#3]
Kafka is just receiving duplicates of the same few metrics.

**Comment by woodsaj** [comment]
@Dieterbe i have fixed this, but for performance improvement we probably need to use the bufPool concept used in metrictank to reduce memory allocations.

**Comment by Dieterbe** [comment]
hmm within one Publish call we should be able to use a singular backing array for all the slices we use for the marshalling, as long as the value used in the message is only the range representing a singular marshal.
sync.Pool should only be needed to reuse the same arrays across different Publish calls.

**Comment by Dieterbe** [comment]
something like this maybe?
```
diff --git a/metric_publish/publish.go b/metric_publish/publish.go
index 9fa0aba..27cd92c 100644
--- a/metric_publish/publish.go
+++ b/metric_publish/publish.go
@@ -85,7 +85,7 @@ func Publish(metrics []*schema.MetricData) error {
        pre := time.Now()
 
        for i, metric := range metrics {
-               data, err = metric.MarshalMsg(data[:])
+               data, err = metric.MarshalMsg(data[len(data):])
                if err != nil {
                        return err
                }
```

not tested yet, have to go afk now

**Comment by Dieterbe** [comment]
i wanna test it a bit more, but it seems to work for me. see #4

**Comment by Dieterbe** [comment]
@woodsaj can we close this?
