### ISSUE TITLE
add support for cortex

### ISSUE THREAD

**Issue by woodsaj** [raintank/tsdb-gw#70]
moving forward we want to be able to support using both metrictank and cortex as a backend TSDB.

This allows us to continue to use tsdb-gw for handling auth, then allow metrics and queries through to either backend.

**Comment by woodsaj** [comment]
cortex expects a "X-Scope-OrgID" header with requests. We should set this orgId to a HostedMetrics instance id, retrieved from grafana.com.

Users currently authenticate via basicAuth, where the username is 'api_key' and the password is a grafana.com api key.  We need to change this so that the username is the instance name instead.
When authenticating the user, we just need to make a call to
```
curl -s -H "Authorization: Bearer <API_KEY>" https://grafana.com/api/hosted-metrics?name=<name>
```
using the apiKey provided by the user to authenticate.

If the key is valid, a 200 response will be returned, else a 401 error will be returned.
If the instance name is valid, the response json will have an array "items: []" with an item in it.  If the array is empty, then the user does not have an instance with the request name and we should reject the auth attempt.

Response for valid instance

statusCode=200
```
{
  "items": [
    {
      "id": 29,
      "orgId": 5000,
      "orgSlug": "grafana",
      "orgName": "Grafana Labs",
      "clusterId": 2,
      "clusterSlug": "us-east",
      "clusterName": "us-east",
      "name": "hg",
      "url": "https://tsdb-5000-hg.hosted-metrics.grafana.net",
      "description": null,
      "createdAt": "2017-04-25T21:59:43.000Z",
      "createdBy": "dcech",
      "updatedAt": null,
      "updatedBy": "",
      "links": [
        {
          "rel": "self",
          "href": "/hosted-metrics/29"
        },
        {
          "rel": "org",
          "href": "/orgs/grafana"
        }
      ]
    }
  ],
  "orderBy": "name",
  "direction": "asc",
  "links": [
    {
      "rel": "self",
      "href": "/hosted-metrics"
    }
  ]
}
```
response when instance doesnt exist

statusCode=200
```
{
  "items": [],
  "orderBy": "name",
  "direction": "asc",
  "links": [
    {
      "rel": "self",
      "href": "/hosted-metrics"
    }
  ]
}
```
response when apiKey is invalid

statusCode=401
```
{
  "code": "InvalidCredentials",
  "message": "Token could not be parsed"
}
```

**Comment by woodsaj** [comment]
@tomwilkie @DanCech

**Comment by DanCech** [comment]
That will work, since I have to update the API anyway to discriminate between MT and cortex instances we can also easily add a dedicated endpoint to make it easier to handle the result in tsdb-gw

**Comment by tomwilkie** [comment]
@jtlisi mentioned he was working on this.

**Comment by jtlisi** [comment]
@woodsaj Working on the new workflow. One question, if an admin user queries the endpoint. If two orgs have a instance with the same name there is no way to specify which backend to set the header for. Also why can't we use the instance Id as the user in basic auth?

**Comment by woodsaj** [comment]
> Also why can't we use the instance Id as the user in basic auth

If that makes it easier to implement, i am all for it.
