### ISSUE TITLE
Local: Queue full metrics

### ISSUE THREAD

**Issue by tehlers320** [raintank/tsdb-gw#77]
If you enable:

` config.SetKey("statistics.interval.ms", "5000")`
and setup something to log the metrics you can view the blocking queue

In my case i adjusted the max.messages to allow 1000000 vs 100000
`config.SetKey("queue.buffering.max.messages", "1000000")`

```
 "msg_cnt":**182288**
 "msg_max":1000000
```

82288 over the normal queue capacity.

The problematic part of this queue is that if you ever reach it tsdb-gw stops publishing to kafka and never recovers. Unfortunately it also still reports as healthy.
![screen shot 2018-03-26 at 5 32 06 pm](https://user-images.githubusercontent.com/16598119/37936571-ae3621d2-311b-11e8-9a99-c37413a91fef.png)

I threw these into the logger on locally published build to look but this may be valuable to other users to have in the tsdb-gw graphed statistics.

**Comment by woodsaj** [comment]
The metric_publisher currently enters a loop that does not exit until all delivery messages are received. If a delivery message is lost, that could lead to a deadlock.
https://github.com/raintank/tsdb-gw/blob/master/metric_publish/publish.go#L189-L212

Perhaps the queue filling up is leading to this issue?

**Comment by Dieterbe** [comment]
looks like errors are also counted toward that number to close the loop. is it possible for a message to get lost? kafka's protocol is a lossless tcp protocol I thought.

note that if you send SIGQUIT to a go process like tsdbgw, it will emit a stack dump
(see https://golang.org/pkg/os/signal/#hdr-Types_of_signals for more info).
that could help in confirming this theory.

**Comment by tehlers320** [comment]
[tsdb-gw-dump.txt](https://github.com/raintank/tsdb-gw/files/1852656/tsdb-gw-dump.txt)

**Comment by Dieterbe** [comment]
looks like @woodsaj's theory checks out. you had a lot of goroutines stuck reading from that channel, for about 9 minutes when you took the dump.

```
grep -B 3 'publish.go:189' tsdb-gw-dump.txt | grep goroutine
goroutine 54 [chan receive, 9 minutes]:
goroutine 1209 [chan receive, 9 minutes]:
goroutine 14 [chan receive, 9 minutes]:
goroutine 2236 [chan receive, 9 minutes]:
goroutine 56 [chan receive, 9 minutes]:
goroutine 16 [chan receive, 9 minutes]:
goroutine 38 [chan receive, 9 minutes]:
goroutine 1725 [chan receive, 9 minutes]:
goroutine 1731 [chan receive, 9 minutes]:
goroutine 49 [chan receive, 9 minutes]:
goroutine 1203 [chan receive, 9 minutes]:
goroutine 88 [chan receive, 9 minutes]:
goroutine 136 [chan receive, 9 minutes]:
goroutine 162 [chan receive, 9 minutes]:
goroutine 139 [chan receive, 9 minutes]:
goroutine 206 [chan receive, 9 minutes]:
goroutine 1010 [chan receive, 9 minutes]:
goroutine 242 [chan receive, 9 minutes]:
goroutine 151 [chan receive, 9 minutes]:
goroutine 164 [chan receive, 9 minutes]:
goroutine 165 [chan receive, 9 minutes]:
goroutine 207 [chan receive, 9 minutes]:
goroutine 344 [chan receive, 9 minutes]:
goroutine 224 [chan receive, 9 minutes]:
goroutine 465 [chan receive, 9 minutes]:
goroutine 1554 [chan receive, 9 minutes]:
goroutine 1090 [chan receive, 9 minutes]:
goroutine 1849 [chan receive, 9 minutes]:
goroutine 1780 [chan receive, 9 minutes]:
goroutine 1712 [chan receive, 9 minutes]:
goroutine 1316 [chan receive, 9 minutes]:
goroutine 599 [chan receive, 9 minutes]:
goroutine 1046 [chan receive, 9 minutes]:
goroutine 1711 [chan receive, 9 minutes]:
goroutine 501 [chan receive, 9 minutes]:
goroutine 2222 [chan receive, 9 minutes]:
goroutine 1555 [chan receive, 9 minutes]:
goroutine 2274 [chan receive, 9 minutes]:
goroutine 1151 [chan receive, 9 minutes]:
goroutine 1612 [chan receive, 9 minutes]:
goroutine 996 [chan receive, 9 minutes]:
goroutine 1617 [chan receive, 9 minutes]:
goroutine 1730 [chan receive, 9 minutes]:
goroutine 1365 [chan receive, 9 minutes]:
goroutine 1744 [chan receive, 9 minutes]:
goroutine 1726 [chan receive, 9 minutes]:
goroutine 1366 [chan receive, 9 minutes]:
goroutine 1636 [chan receive, 9 minutes]:
goroutine 1465 [chan receive, 9 minutes]:
goroutine 2034 [chan receive, 9 minutes]:
goroutine 1901 [chan receive, 9 minutes]:
goroutine 1724 [chan receive, 9 minutes]:
goroutine 1819 [chan receive, 9 minutes]:
goroutine 1858 [chan receive, 9 minutes]:
goroutine 2227 [chan receive, 9 minutes]:
goroutine 1850 [chan receive, 9 minutes]:
goroutine 1863 [chan receive, 9 minutes]:
goroutine 1864 [chan receive, 9 minutes]:
goroutine 2261 [chan receive, 9 minutes]:
goroutine 2058 [chan receive, 9 minutes]:
goroutine 2276 [chan receive, 9 minutes]:
goroutine 1951 [chan receive, 9 minutes]:
goroutine 2043 [chan receive, 9 minutes]:
goroutine 1980 [chan receive, 9 minutes]:
goroutine 2023 [chan receive, 9 minutes]:
goroutine 2229 [chan receive, 9 minutes]:
goroutine 2032 [chan receive, 9 minutes]:
```

**Comment by woodsaj** [comment]
I have been able to replicate this locally, but have not dived into what is causing it yet.
to replicate i
1) bring up tsdb-gw and kafka (using this docker-compose file. https://gist.github.com/woodsaj/1bf0a441850a0dc4c64bdd2b51b95e39)
2) send metrics to tsdb-gw (i used haggar sending to a local carbon-relay-ng, sending at 10k/second)
3) let the metric volume stabilize
4) restart kafka.

**Comment by woodsaj** [comment]
the deadlock is occuring when the kafka lib is unable to push messages down the deliveryChan.
https://github.com/raintank/tsdb-gw/blob/master/vendor/github.com/confluentinc/confluent-kafka-go/kafka/event.go#L237-L241

Making the DeliveryChan buffer (with `len(metrics)`) appears to fix the issue.
https://github.com/raintank/tsdb-gw/blob/master/metric_publish/publish.go#L146

But i am still not clear on why this is all happening.

**Comment by woodsaj** [comment]
Ok, the issue is a race condition.
All messages in a batch are sent to the producer before we start to read from the deliveryChan.

If the librdkafka queue size is 100, but 101 metrics are sent in a single batch to metric_publish.Publish(), then the first 100 metrics will be queued, but the last one will be blocked as the queue is full.  The queue wont be drained until we start reading from the deliveryChan, but that will never happen was the full queue error causes an early return.

So the best solution here is to just make the deliveryChan buffered.
