### ISSUE TITLE
tsdb-gw: carbon direct input broken

### ISSUE THREAD

**Issue by Dieterbe** [raintank/tsdb-gw#95]
0.8.0-117-gaf82d93 does not seem to work
0.7.0-19-g1454a2d works

**Comment by jtlisi** [comment]
@Dieterbe I took a look, it seems that carbon is defaulting to file auth which is causing it not to start. I changed it in #100

**Comment by woodsaj** [comment]
the carbon input has always used fileauth.  for prod deployments, hm-api includes an auth-file on the instances configmap, which is mounted into the tsdb-gw containers.

**Comment by woodsaj** [comment]
this was resolved
